[package]
name = "master-clock"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
eframe = "0.29"
dark-light = "2"
ureq = "2"
serde_json = "1"
litcrypt = "0.4.0"
windows = { version = "0.58", features = [
    "Win32_System_SystemInformation",
    "Win32_System_Performance",
    "Win32_System_Power",
    "Win32_System_Time",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_Foundation",
] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
